feedhenry/nagios-container

- README.md
- fhservices.cfg.j2
*  The value in the services array should be the service name to look for in openshift.
* Update README based on repo name change. No specific (wrong or otherwise) version mentioned.
> Remove appending of '-service' to service names.

- Dockerfile
> fix missing &&

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
* Adds a new health check for millicore 	7f57c2c
* Modifies the way the services are generated to allow more reuse  4c0d231
Requires https://github.com/feedhenry/nagios-container/pull/14 to be merged first.
Jira:
https://issues.jboss.org/browse/RHMAP-8088
> Rhmap 8088 add millicore check

- make-nagios-fhservices-cfg
* Add UPS health check
Jira:
https://issues.jboss.org/browse/RHMAP-8089
> RHMAP-8089 - Add UPS health check

- .travis.yml
- README.md
- plugins/default/lib/disk_usage.py
- plugins/default/lib/nagios.py
- plugins/default/lib/openshift.py
- plugins/default/lib/test_disk_usage.py
- plugins/default/lib/test_openshift.py
- setup.cfg
* Adds a travis build file, runs pep8 and unit tests
* Executed autopep8 on all existing plugins (no functional changes)
* Add build status to readme
Jira:
https://issues.jboss.org/browse/RHMAP-9094
> Rhmap 9094 add travis file

- make-nagios-fhservices-cfg
* Adds fh-scm health and ping checks
Jira:
https://issues.jboss.org/browse/RHMAP-9279
> RHMAP-9279 - Add fh-scm health and ping checks

- fhservices.cfg.j2
- plugins/default/lib/mysql_health.py
- plugins/default/lib/openshift.py
- plugins/default/lib/test_mongodb_health.py
- plugins/default/mysql-health
Also, added additional mongodb container name variation (handles most recent single node mbaases)
> add mysql check

- plugins/default/lib/openshift.py
**JIRA**
https://issues.jboss.org/browse/RHMAP-14104
@psturc 
Also removing an out of date comment
> update args to fix error message in mbaas

- README.md
- fhservices.cfg.j2
- make-nagios-fhservices-cfg
- plugins/default/android_sdk_health
- plugins/default/ios_machine_health
- plugins/default/lib/android_sdk_health.py
- plugins/default/lib/ios_machine_health.py
- plugins/default/lib/test_android_sdk_health.py
- plugins/default/lib/test_ios_machine_health.py
**JIRA**
https://issues.jboss.org/browse/RHMAP-16489
**Changes**
- define hostgroup digger
- define service jenkins
- define command check_jenkins
- Add digger to Memory, Resource etc. checks
**Verification**
Docker image build and pushed to docker hub tag: digger-test
This image is deployed to OSM4 digger project nagios pod
> add nagios checks for digger

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
> Base valid digger checks on env var

- Jenkinsfile
Backport of https://github.com/feedhenry/nagios-container/pull/56
> Add Jenkinsfile with openshift build image stage.

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
- plugins/default/lib/ios_machine_health.py
Nagios should do Jenkins check on sdn as opposed to hitting the external route
> ios check should use internal dns

- plugins/default/lib/test_android_pvc_check.py
**JIRA**
https://issues.jboss.org/browse/AGDIGGER-139
**Changes**
Add in test
**Verification**
Run tests
```
python -m unittest discover -s plugins/default
```
Tests should pass
> add tests for androidpvc check

- README.md
- plugins/default/lib/android_pvc_check.py
> Update exception handling for flake8

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
- plugins/default/lib/mysql_master_slave_health.py
- plugins/default/mysql-master-slave-health
**JIRA**
https://issues.jboss.org/browse/RHMAP-19372
> RHMAP-19372 added mysql master/slave check to nagios

- fhservices.cfg.j2
- plugins/default/check_fhmessaging_collections
- plugins/default/lib/check_fhmessaging_collections.py
- plugins/default/lib/test_check_fhmessaging_collections.py
JIRA: https://issues.jboss.org/browse/RHMAP-19894
> Check to ensure the fh-messaging collections get created daily

- fhservices.cfg.j2
- plugins/default/lib/mongodb_affinity.py
- plugins/default/lib/openshift.py
- plugins/default/mongodb-affinity
> initial commit of nagios check

- Dockerfile
- README.md
- fhservices.cfg.j2
- make-nagios-fhservices-cfg
- plugins/default/lib/mongodb_affinity.py
- plugins/default/lib/mongodb_health.py
- plugins/default/lib/openshift.py
- plugins/default/lib/pod_affinity.py
https://issues.jboss.org/browse/RHMAP-21515
Had to resolve a few problems which were preventing mongo checks from working with alternate projects.  One check is still going to fail on OSD but thats due to service account permissions which will need to be addressed as an upgrade/install step.
> Rhmap 21515 mongo monitor

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
Uses a list o generate mysql nagios checks for all hosts
> mysql service list

- make-nagios-fhservices-cfg
Only adds userspace mongodb nagios check if USERDATA_PROJECT_NAME env var is defined
> userpace project name env var

- make-nagios-fhservices-cfg
> Rhmap 21535 fh v4.7

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
> Rhmap 21696 mysql check fix fh v4.7

- .github/pull_request_template.md
> Added a Github PR Template

- .github/pull_request_template.md
- fhservices.cfg.j2
- plugins/default/disk-usage-mongo
- plugins/default/lib/disk_usage_mongo.py
- https://issues.jboss.org/browse/RHMAP-20790
Merging to release branch to be included in 4.7.1
To ensure that FHOPS has the ability to monitor the volumes inside MongoDB instances singularly or within a replicaset.
> cherry-pick RHMAP-20790 Mongo volume check fh4.7
