feedhenry/nagios-container

- Dockerfile
- fhservices.cfg.j2
- make-nagios-fhservices-cfg
- plugins/default/fh-check-component-health.sh
* Adds checks for all the core node.js components
* Adds a new nagios module for querying the health endpoint (Copied from an existing check)
Some cross over with https://github.com/feedhenry/nagios-container/pull/5 regarding nagios plugins setup.
Note:
Currently the fh-appstore doesn't have the health endpoint so fails all the time.
> Rhmap 6722 add node core component checks

- Dockerfile
This adds the OSE client tools which provide oc which will be especially useful for its exec functionality when creating nagios checks with probe into the running pods.
> RHMAP-8410 install oc tools

- fhservices.cfg.j2
As check uses the existing nagios check_tcp plugin, there was no need for additional python plugins. Only change required was a new command and service in the fhservices.cfg.j2 file
@jessesarn @mikenairn @rhcarvalho mind taking a look?
> Adding tcp check for memcached

- fhservices.cfg.j2
Adding custom health check for Keycloak. Not adding this to the standard block of health checks as the Keycloak endpoint has an expected HTTP 302 redirect response which needs to be handled by the standard check_http nagios plugin.
Related Jira:
https://issues.jboss.org/browse/RHMAP-8091
> Adding keycloak health endpoint check

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
* Allows the nagios image to be shared between both the rhmap core and mbaas.
* Uses an env var to switch between the 2 or both (RHMAP_HOSTGROUPS='core'|'mbaas'|'core,mbaas')
* Uses nagios hostgroups to determine what checks should be applied to what, all services must have a hostgroup_name set on them.
Jira:
https://issues.jboss.org/browse/RHMAP-8605
> Rhmap 8605 use hostgroups for core or mbaas

- .flake8
- .travis.yml
- README.md
- plugins/default/lib/disk_usage.py
- plugins/default/lib/openshift.py
- plugins/default/lib/test_disk_usage.py
- setup.cfg
- Run `flake8` instead of `pep8` on all Python code in the repository
- Suggest auto-formatting all files
- Update README.md
> Use flake8 instead of pep8

- plugins/default/lib/component_health.py
- plugins/default/lib/disk_usage.py
This is making the structure of the existing checks more similar to facilitate adding new checks in the same style.
Each script looks like:
```python
#!/usr/bin/env python
import ...
import sys
import traceback
import nagios
def generate_parser():
parser = argparse.ArgumentParser(
description="...",
)
parser.add_argument(
)
return parser
def check(...):
return nagios.OK
if __name__ == "__main__":
args = generate_parser().parse_args()
code = nagios.UNKNOWN
try:
code = check(...)
except:
traceback.print_exc()
finally:
sys.exit(code)
```
The functional changes squeezed in here:
- The `fh-check-component-health` check returns `UNKNOWN` instead of `CRIT` for connection errors
- Fixed exit codes for `disk-usage` check:  it only ever returned 0 (implicit when the script terminates) or UNKNOWN in …
> Uniform checks

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
This change is required to support the existing 3 node mbaas template where the service names are different to what we have in our core templates, see related Jira.
**Related Jira**
https://issues.jboss.org/browse/RHMAP-9521
**Validation**
Deploy version 4.0.8-93 of the nagios docker image within a Core and MBaaS project. Ensure all expected checks are displayed and passing
> Adding support for mbaas 3 node template

- fhservices.cfg.j2
**Overview**
At the moment our MBaaS 3 node template does not have a requirement to have parameters passed in for MBAAS_ROUTER_DNS. When adding Nagios to this template, there is an issue where the nagios host does not get set due to MBAAS_ROUTER_DNS not being passed in. To resolve this issue, we need to instead update the MBaaS 3 node template to use localhost by default and change the default host health check to use check_ping rather than check_http as localhost on Nagios does not have 80 or 443 port running.
**Related Jiras:**
https://issues.jboss.org/browse/RHMAP-9693
**Validation**
Use this Nagios image (docker.io/rhmap/nagios4:4.0.8-96
as part of a Core and MBaaS project and ensure that the Nagios host is not showing up as red
> Updating nagios host alive check to use check_ping plugin

- fhservices.cfg.j2
- plugins/default/lib/disk_usage.py
- plugins/default/lib/memory_usage.py
- plugins/default/lib/openshift.py
- plugins/default/lib/test_memory_usage.py
- plugins/default/memory-usage
* Adds new memory nagios checks. Will warn of any issues in running containers that have a memory limit set (Future work to check that limits have been set)
* Adds an optional 'project' argument to both the memory and disk checks to make them easier to test. Default is still the currently configured openshift namespace as before.
```
$ ./memory-usage -w 80 -c 90 -p core
OK: All 6 containers are under the warning threshold
OK: fh-messaging-1-i9zy8: - total bytes: 419430400.0 used bytes: 131399680.0 usage: 31.3%
OK: fh-metrics-1-73ho5: - total bytes: 419430400.0 used bytes: 75399168.0 usage: 18.0%
OK: memcached-1-xrabe: - total bytes: 1073741824.0 used bytes: 18030592.0 usage: 1.7%
OK: mongodb-1-1-olaua: - total bytes: 1048576000.0 used bytes: 145178624.0 usage: 13.8%
OK: mysql-1-g3eu1: - …
```
> Rhmap 9311 memory checks

- .gitignore
- fhservices.cfg.j2
- plugins/default/cpu-usage
- plugins/default/lib/cpu_usage.py
- plugins/default/lib/test_cpu_usage.py
* Adds a new nagios check for CPU usage based on the limits set for the container. Uses the time elapsed between checks to work out how much CPU time was used. 
* Will display UNKNOWN status on the initial check since it requires 2 successful checks to take place before it can start calculating usage.
Jira:
https://issues.jboss.org/browse/RHMAP-9312
> RHMAP-9312 - Add container cpu usage nagios check

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
* Add ping checks for millicore and ups.
* Modified check_fh_component_http_ping to use args being passed to it.
Jira:
https://issues.jboss.org/browse/RHMAP-9870
> RHMAP-9870 - Add ping checks for millicore and ups.

- fhservices.cfg.j2
- plugins/default/lib/cpu_usage.py
- plugins/default/lib/memory_usage.py
* Rename mongodb replicaset health check
* Only apply replicaset check to the mbaas.
* Fix an issue where the cpu check wasn't working for pods with more than one container.
* Add pod and container name to memory and cpu check output: 
```
$ ./cpu-usage -c 90 -w 80 -p core
...
OK: millicore-1-topoi:millicore: - usage: 0.35%
OK: millicore-1-topoi:rhmap-proxy: - usage: 0.16%
OK: millicore-1-topoi:feedhenry-sdks: - usage: 0.15%
...
```
Jira:
https://issues.jboss.org/browse/RHMAP-9900
> RHMAP-9900 - Remove incompatible mongodb check from core

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
JIRA: [RHMAP-9934](https://issues.jboss.org/browse/RHMAP-9934)
Adds mongodb "ping" checks via check_tcp, adds support for make-nagios-fhservices-cfg script to determine the names of the mongodb service(s) based on template parameters (core vs. mbaas).  Defaults to 3 for mbaas if parameter is not found as the 1 node mbaas template doesn't include nagios anyway.
> add mongodb ping check

- fhservices.cfg.j2
- plugins/default/lib/resource_limits.py
- plugins/default/lib/test_resource_limits.py
- plugins/default/resource-limits
Adds a new nagios check that warns if any running containers do not have a resource limit set for memory or cpu.
Jira:
https://issues.jboss.org/browse/RHMAP-9527
> RHMAP-9527 - Nagios check for resource limits (CPU/Memory)

- start
**Overview**
In this sprint we have a task to add support for persistent volumes in Nagios. However, an issue was uncovered where some log directories are not being created on startup causing the Nagios dashboard services page to throw an error. As it turns out we used to create these directories as part of startup in the mbaas-monitoring repo [1]
[1] https://github.com/feedhenry/mbaas-monitoring/blob/master/start.sh#L4-L6
**Related Jiras**
https://issues.jboss.org/browse/RHMAP-10153
> RHMAP-10153: Creating log dirs in start.sh script to support PVs

- Dockerfile
- scripts/check-status
- scripts/host-svc-check
Adds 2 helper scripts that can be used during dev or on CI to check the status of nagios.
**host-svc-check**
Schedules a check of all services for the currently configured host (RHMAP_ROUTER_DNS). Takes into account that the CPU check potentially requires 2 runs before it will be OK. 
Test inside container:
```
[vagrant@ose32 ~]$ oc rsh nagios-2-6i3wq 
sh-4.2$ /opt/rhmap/host-svc-check 
Forcing service checks on 'localhost' ...
Waiting 20s ...
Forcing service checks on 'localhost' ...
Waiting 20s ...
Done, all service checks should be up to date.
```
**check-status**
Get the service status of the currently configured host (RHMAP_ROUTER_DNS). Returns a non zero exit status if any of the service checks are not OK, or there are no service checks for the host. Makes use of the jsonquery …
> Rhmap 10225 status helper scripts

- fhservices.cfg.j2
Rename redis and memcached ping to match all other checks and use uppercase p ping -> Ping
> Consistent naming of ping checks

- scripts/host-svc-check
Updated host-svc-check helper script to take optional args for times and delay. Can be useful for testing certain scenarios to have control over this.
From inside container:
```
$ /opt/rhmap/host-svc-check --times=1 --delay=5
Forcing service checks on 'localhost' (1/1) ...
Waiting 5s ...
Done, all service checks should be up to date.
```
From OS VM:
```
$ oc exec -ti "$(oc get pods | grep nagios | awk '{print $1}')" -- /opt/rhmap/host-svc-check --times=1 --delay=5
```
> RHMAP-10225 - Updated host-svc-check helper script

- fhservices.cfg.j2
- make-nagios-fhservices-cfg
Uses "MONGODB_ENDPOINT_COUNT" env var in jinja template to include or not replica set monitor (default value is 3).
This wat env var can be set from openshift template param.
> usage of MONGODB_ENDPOINT_COUNT in template

- .travis.yml
- make-nagios-fhservices-cfg
**JIRA**
https://issues.jboss.org/browse/RHMAP-19337
**Changes**
by removing the project check (as it is irrelevant now) the python should always pick up on the env var set from the installer.
> remove project check

- fhservices.cfg.j2
- plugins/default/lib/openshift.py
- plugins/default/lib/pod_affinity.py
- plugins/default/pod-affinity
**Summary**
In a HA Openshift environment a component with multiple identical pods should have these pods running on separate nodes. This check will issue a warning message should it find two identical pods running on the same node. It is then up to the cluster administrator to determine whether or not these pods should be moved/re-scheduled.
**Validation**
Scale a component to a minimum of 2 pods on the same Openshift node. The expected outcome of the check should be similar to the below example:
```
WARN: redis has 2 pods running on the same node: <node-name>
```
Now schedule these 2 pods to run on separate Openshift nodes. The expected outcome should be:
```
OK: Component pod distribution as expected
```
> Adding new plugin for pod affinity validation

- fhservices.cfg.j2
https://issues.jboss.org/browse/RHMAP-20519
Modify check interval of services (1 for database services, 5 for all other)
Don't count the `/etc/hosts` to create disk usage alerts in the Nagios
The 10 minute interval is too long before NOC may be informed.  Also increase reliability of status information when following status-dependent procedures in documentation and/or automation.
Add new service templates, one for database services which overrides check interval to 1 and another for the other services which overrides check interval to 5.
1. Log into nagios
2. Bring up service details and note latest check times
2. Wait at least 60 seconds
3. Refresh the service status details and compare latest check times of mysql and mongodb checks to confirm that the latest check times changed.
4. Wait …
> modified check intervals from 10 to 1/5

- Dockerfile
- plugins/default/lib/openshift.py
JIRA: https://issues.jboss.org/browse/RHMAP-21670
In `oc` 3.10, if the `--show-all` parameter is used for `oc get`, then a deprecation warning is output along with the regular output. When this python script tries to decode the whole output to JSON, it fails (even though the regular output without the warning is valid and decode-able).
Given that this parameter appears to have been arbitrarily changed from `--show-all=false` to `--show-all=true` in [1] just to get around some other issue with a different `oc` version, I think it's fine to just remove it.
[1] https://github.com/feedhenry/nagios-container/pull/48
> 👽 Remove --show-all for oc 3.10

- Dockerfile
- plugins/default/lib/openshift.py
JIRA: https://issues.jboss.org/browse/RHMAP-21670
In `oc` 3.10, if the `--show-all` parameter is used for `oc get`, then
a deprecation warning is output along with the regular output. When
this python script tries to decode the whole output to JSON, it
fails (even though the regular output without the warning is valid and
decode-able).
Given that this parameter appears to have been arbitrarily changed
from `--show-all=false` to `--show-all=true` in [1] just to get around
some other issue with a different `oc` version, I think it's fine to
just remove it.
[1] https://github.com/feedhenry/nagios-container/pull/48
> 👽 Remove --show-all for oc 3.10 (cherry-pick for FH-v4.7)
